In [19]:
import numpy as np

A = np.array([[1,2,3,4],[5,6,7,8],[ 6,8, 10, 12]]);
A= A+100
print(A)

[[101 102 103 104]
 [105 106 107 108]
 [106 108 110 112]]


In [20]:
cal = A.sum(axis=0);
cal2 = A.sum(axis=1);

In [21]:
print(A)
print(cal)
print(cal2)

[[101 102 103 104]
 [105 106 107 108]
 [106 108 110 112]]
[312 316 320 324]
[410 426 436]


In [33]:
a = np.random.randn(1,2)
print(a)
assert(a.shape == (2,1))
print(a.shape)

[[ 0.77553798 -1.08287983]]


AssertionError: 