# numpy练习
 非代码部分使用markdown文档

In [45]:
import numpy as np
a = np.random.randn(5,1)
b = np.random.randn(1,5)

assert(b.shape == (1, 5)) #保证程序像自己想象的那样运行

print(a)
print(b)

[[-0.44924199]
 [ 0.63457184]
 [ 1.52037463]
 [-0.79687041]
 [ 0.12887149]]
[[-1.14686392  0.17933285 -0.21841383  0.11599073  0.92248528]]


In [34]:
print(a.shape)

(5, 1)


In [35]:
print(a.T)

[[ 0.7176935  -1.21756103  0.18488831  1.89626704  0.44504821]]


In [38]:
print(np.dot(a, a.T))

[[ 0.51508395 -0.87383563  0.13269314  1.36093852  0.3194082 ]
 [-0.87383563  1.48245486 -0.22511281 -2.30882085 -0.54187335]
 [ 0.13269314 -0.22511281  0.03418369  0.35059762  0.08228421]
 [ 1.36093852 -2.30882085  0.35059762  3.59582867  0.84393025]
 [ 0.3194082  -0.54187335  0.08228421  0.84393025  0.19806791]]
